version: '3'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER: root
      # MYSQL_PASSWORD: admin
    command: --default-authentication-plugin=mysql_native_password
  
    volumes :
      - ./dbdata:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/host/data:/data 
     
  app:
    build: .
    # command: python3 index.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
